export const HOUSEHOLD_PERMISSIONS = {
  // Account management
  MANAGE_ACCOUNTS: 'manage_accounts',
  VIEW_ALL_ACCOUNTS: 'view_all_accounts',
  CREATE_ACCOUNTS: 'create_accounts',
  DELETE_ACCOUNTS: 'delete_accounts',

  // Transaction management
  MANAGE_TRANSACTIONS: 'manage_transactions',
  VIEW_ALL_TRANSACTIONS: 'view_all_transactions',
  CREATE_TRANSACTIONS: 'create_transactions',
  DELETE_TRANSACTIONS: 'delete_transactions',
  CATEGORIZE_TRANSACTIONS: 'categorize_transactions',

  // Budget management
  MANAGE_BUDGETS: 'manage_budgets',
  VIEW_BUDGETS: 'view_budgets',
  CREATE_BUDGETS: 'create_budgets',
  DELETE_BUDGETS: 'delete_budgets',

  // Debt management
  MANAGE_DEBTS: 'manage_debts',
  VIEW_DEBTS: 'view_debts',
  CREATE_DEBTS: 'create_debts',
  DELETE_DEBTS: 'delete_debts',

  // Wishlist management
  MANAGE_WISHLIST: 'manage_wishlist',
  VIEW_WISHLIST: 'view_wishlist',
  CREATE_WISHLIST_ITEMS: 'create_wishlist_items',
  DELETE_WISHLIST_ITEMS: 'delete_wishlist_items',

  // Reports and analytics
  VIEW_REPORTS: 'view_reports',
  EXPORT_DATA: 'export_data',
  VIEW_ANALYTICS: 'view_analytics',

  // Household management
  MANAGE_MEMBERS: 'manage_members',
  INVITE_MEMBERS: 'invite_members',
  REMOVE_MEMBERS: 'remove_members',
  MANAGE_SETTINGS: 'manage_settings',

  // OCR and document processing
  USE_OCR: 'use_ocr',
  UPLOAD_DOCUMENTS: 'upload_documents',

  // Gratitude entries
  MANAGE_GRATITUDE: 'manage_gratitude',
  VIEW_GRATITUDE: 'view_gratitude',
} as const;

export type HouseholdPermission = typeof HOUSEHOLD_PERMISSIONS[keyof typeof HOUSEHOLD_PERMISSIONS];

// Default permissions for each role
export const DEFAULT_ROLE_PERMISSIONS = {
  ADMIN: Object.values(HOUSEHOLD_PERMISSIONS),
  PARTNER: [
    HOUSEHOLD_PERMISSIONS.VIEW_ALL_ACCOUNTS,
    HOUSEHOLD_PERMISSIONS.CREATE_ACCOUNTS,
    HOUSEHOLD_PERMISSIONS.MANAGE_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.VIEW_ALL_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.CREATE_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.CATEGORIZE_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.MANAGE_BUDGETS,
    HOUSEHOLD_PERMISSIONS.VIEW_BUDGETS,
    HOUSEHOLD_PERMISSIONS.CREATE_BUDGETS,
    HOUSEHOLD_PERMISSIONS.MANAGE_DEBTS,
    HOUSEHOLD_PERMISSIONS.VIEW_DEBTS,
    HOUSEHOLD_PERMISSIONS.CREATE_DEBTS,
    HOUSEHOLD_PERMISSIONS.MANAGE_WISHLIST,
    HOUSEHOLD_PERMISSIONS.VIEW_WISHLIST,
    HOUSEHOLD_PERMISSIONS.CREATE_WISHLIST_ITEMS,
    HOUSEHOLD_PERMISSIONS.VIEW_REPORTS,
    HOUSEHOLD_PERMISSIONS.VIEW_ANALYTICS,
    HOUSEHOLD_PERMISSIONS.USE_OCR,
    HOUSEHOLD_PERMISSIONS.UPLOAD_DOCUMENTS,
    HOUSEHOLD_PERMISSIONS.MANAGE_GRATITUDE,
    HOUSEHOLD_PERMISSIONS.VIEW_GRATITUDE,
  ],
  FINANCE_STAFF: [
    HOUSEHOLD_PERMISSIONS.VIEW_ALL_ACCOUNTS,
    HOUSEHOLD_PERMISSIONS.CREATE_ACCOUNTS,
    HOUSEHOLD_PERMISSIONS.MANAGE_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.VIEW_ALL_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.CREATE_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.CATEGORIZE_TRANSACTIONS,
    HOUSEHOLD_PERMISSIONS.VIEW_BUDGETS,
    HOUSEHOLD_PERMISSIONS.VIEW_DEBTS,
    HOUSEHOLD_PERMISSIONS.VIEW_WISHLIST,
    HOUSEHOLD_PERMISSIONS.VIEW_REPORTS,
    HOUSEHOLD_PERMISSIONS.USE_OCR,
    HOUSEHOLD_PERMISSIONS.UPLOAD_DOCUMENTS,
    HOUSEHOLD_PERMISSIONS.VIEW_GRATITUDE,
  ],
} as const;
