global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Permoney Backend Application
  - job_name: 'permoney-backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/health/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Health Check Endpoints
  - job_name: 'permoney-health'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/health'
    scrape_interval: 60s
    scrape_timeout: 10s
