export enum EventType {
  TRANSACTION_CREATED = 'transaction.created',
  TRANSACTION_UPDATED = 'transaction.updated',
  TRANSACTION_DELETED = 'transaction.deleted',
  TRANSACTION_CATEGORIZED = 'transaction.categorized',
  TRANSACTION_SPLIT = 'transaction.split',
  BUDGET_CREATED = 'budget.created',
  BUDGET_UPDATED = 'budget.updated',
  BUDGET_DELETED = 'budget.deleted',
  BUDGET_OVERSPENT = 'budget.overspent',
  BUDGET_THRESHOLD_REACHED = 'budget.threshold.reached',
  BUDGET_PERIOD_ENDED = 'budget.period.ended',
  BUDGET_CARRYOVER_CREATED = 'budget.carryover.created',
  ACCOUNT_CREATED = 'account.created',
  ACCOUNT_UPDATED = 'account.updated',
  ACCOUNT_DELETED = 'account.deleted',
  HOUSEHOLD_CREATED = 'household.created',
  HOUSEHOLD_UPDATED = 'household.updated',
  USER_JOINED_HOUSEHOLD = 'user.joined.household',
  USER_LEFT_HOUSEHOLD = 'user.left.household',
}
